server:
  port: 6666
  
jwt:
  secret: 'passwordpasswordpasswordpasswordpassword12345678910'
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_portal_v1
    password: Root@123
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
#      
    
